# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DLCImporter": "00_dlc_importer.ipynb",
         "PigeonAnimator": "00_dlc_importer.ipynb",
         "PigeonAnimatorFactory": "00_dlc_importer.ipynb"}

modules = ["dlc_importer.py"]

doc_url = "https://kiview.github.io/winkie/"

git_url = "https://github.com/kiview/winkie/tree/master/"

def custom_doc_links(name): return None
