# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DLCImporter": "00_dlc_importer.ipynb",
         "transform_to_relative": "00_dlc_importer.ipynb",
         "add_middle_neck": "00_dlc_importer.ipynb",
         "add_rotation": "00_dlc_importer.ipynb",
         "apply_rotation": "00_dlc_importer.ipynb",
         "PigeonAnimator": "01_pigeon_animator.ipynb",
         "PigeonAnimatorFactory": "01_pigeon_animator.ipynb",
         "LabelAssistant": "03_label_assistant.ipynb",
         "build_timeseries": "04_ml.ipynb",
         "build_sliding_timeseries": "04_ml.ipynb",
         "build_model": "04_ml.ipynb",
         "build_lstm_model": "04_ml.ipynb",
         "gpus": "04_ml.ipynb"}

modules = ["dlc_importer.py",
           "pigeon_animator.py",
           "label_assistant.py",
           "ml.py"]

doc_url = "https://kiview.github.io/winkie/"

git_url = "https://github.com/kiview/winkie/tree/master/"

def custom_doc_links(name): return None
