# AUTOGENERATED! DO NOT EDIT! File to edit: 00_dlc_importer.ipynb (unless otherwise specified).

__all__ = ['DLCImporter', 'transform_to_relative', 'add_middle_neck', 'add_rotation', 'apply_rotation']

# Cell
import pandas as pd

class DLCImporter:
    """Used to import DLC result files."""

    def import_hdf(self, file):
        df = pd.read_hdf(file)
        df.columns = df.columns.droplevel(0) # drop redundant scorer
        return df

# Cell
def transform_to_relative(df, bodypart):
    df_rel = df.copy()

    for bp in df.columns.levels[0]:
        df_rel[bp, 'x'] = df[bp, 'x'] - df[bodypart, 'x']
        df_rel[bp, 'y'] = df[bp, 'y'] - df[bodypart, 'y']

    return df_rel

# Cell
def add_middle_neck(df):
    df_middle_neck = df.copy()
    df_middle_neck['middle_neck', 'x'] = (df_middle_neck['left_neck','x'] + df_middle_neck['right_neck', 'x']) / 2
    df_middle_neck['middle_neck', 'y'] = (df_middle_neck['left_neck','y'] + df_middle_neck['right_neck', 'y']) / 2
    return df_middle_neck

# Cell
def add_rotation(df):
    df = df.copy()
    df['rotation_angle'] = np.degrees(np.arctan2(df['middle_neck', 'y'], df['middle_neck', 'x']))
    return df

# Cell
def apply_rotation(df):
    df = df.copy()
    df.apply(_rotate_row, axis=1)
    return df