# AUTOGENERATED! DO NOT EDIT! File to edit: 00_dlc_importer.ipynb (unless otherwise specified).

__all__ = ['DLCImporter', 'transform_to_relative']

# Cell
import pandas as pd

class DLCImporter:
    """Used to import DLC result files."""

    def import_hdf(self, file):
        df = pd.read_hdf(file)
        df.columns = df.columns.droplevel(0) # drop redundant scorer
        return df

# Cell
def transform_to_relative(df, bodypart):
    df_rel = df.copy()

    for bp in df.columns.levels[0]:
        df_rel[bp, 'x'] = df[bp, 'x'] - df[bodypart, 'x']
        df_rel[bp, 'y'] = df[bp, 'y'] - df[bodypart, 'y']

    return df_rel