# AUTOGENERATED! DO NOT EDIT! File to edit: 03_label_assistant.ipynb (unless otherwise specified).

__all__ = ['LabelAssistant']

# Cell
import os
import pandas as pd

class LabelAssistant:
    """Used to label data and generate labelled data."""

    def __init__(self, behaviors, data_path):
        self.behaviors = behaviors
        self.files = os.listdir(data_path)
        self.labels = {'behavior': [], 'start': [], 'end': [], 'file': []}

    def addLabel(self, behavior, start_frame, end_frame, file_name):
        if behavior not in self.behaviors:
            raise ValueError(f"Unknown behaviour: {behavior}")
        if file_name not in self.files:
            raise FileNotFoundError(file_name)
        self.labels['behavior'].append(behavior)
        self.labels['start'].append(start_frame)
        self.labels['end'].append(end_frame)
        self.labels['file'].append(file_name)

    def to_df(self):
        return pd.DataFrame(self.labels)


